version: "3"

volumes:
  postgres_data:
services:

  # open telemetry collector
  collector:
    image: otel/opentelemetry-collector-contrib:0.72.0
    command: ["--config=/conf/collector-config.yaml"]
    volumes:
      - ./otel/collector-config.yaml:/conf/collector-config.yaml
    ports:
      - "9464:9464"
      - "4317:4317"
      - "4318:4318"
  # prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  # grafana
  grafana:
    image: grafana/grafana:9.0.1
    container_name: grafana
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3001:3001"

  # database
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: defaultuser
      POSTGRES_PASSWORD: defaultpassword
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgresql/init-db.sh:/docker-entrypoint-initdb.d/init.sql

  # rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./rabbitmq/init.sh:/docker-entrypoint-init-rabbitmq.d/init-rabbitmq.sh
    ports:
      - 15672:15672  # RabbitMQ management UI
      - 5672:5672    # RabbitMQ service

  # jaeger
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686
      - 14250:14250

  # external service
  configuration-service:
    image: igoreulalio/configuration-service:v3
    platform: linux/amd64
    ports: 
      - 8081:8081
    environment:
      - SERVICE_NAME=configuration-service
      - OTEL_COLLECTOR_ENDPOINT=collector
      - REDIS_ADDRESS=redis:6379
      

  # external service database dependency
  redis: 
    image: redis:latest
    volumes:
      - ./redis/init-redis.sh:/usr/local/bin/init-redis.sh
    entrypoint: ["/usr/local/bin/init-redis.sh"]
    ports:
      - 6379:6379

  # external worker
  repository-worker:
    image: igoreulalio/repository-worker:v4
    platform: linux/amd64
    environment:
      - SERVICE_NAME=repository-worker
      - RABBITMQ_HOST=rabbitmq
      - OTEL_COLLECTOR_ENDPOINT=collector
      - DB_HOST=db

  # frontend
  repository-frontend:
    image: igoreulalio/repository-frontend:v2
    platform: linux/amd64
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    ports:
      - 3000:3000