version: "3"

volumes:
  postgres_data:
services:

  collector:
    image: otel/opentelemetry-collector-contrib:0.72.0
    command: ["--config=/conf/collector-config.yaml"]
    volumes:
      - ./otel/collector-config.yaml:/conf/collector-config.yaml
    ports:
      - "9464:9464"
      - "4317:4317"
      - "4318:4318"
  # Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  # Grafana
  grafana:
    image: grafana/grafana:9.0.1
    container_name: grafana
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"

  # Database
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: defaultuser
      POSTGRES_PASSWORD: defaultpassword
      POSTGRES_DB: repositories
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgresql/init-db.sh:/docker-entrypoint-initdb.d/init.sql
  
  # jaeger
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686
      - 14250:14250

  # external service
  configuration-service:
    image: igoreulalio/configuration-service:v2
    platform: linux/amd64
    ports: 
      - 8081:8081
    environment:
      - OTEL_COLLECTOR_ENDPOINT=collector
      - REDIS_ADDRESS=redis:6379
      - SERVICE_NAME=configuration-service

  redis: 
    image: redis:latest
    volumes:
      - ./redis/init-redis.sh:/usr/local/bin/init-redis.sh
    entrypoint: ["/usr/local/bin/init-redis.sh"]
    ports:
      - 6379:6379