apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: golang-api
  name: golang-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golang-api
  strategy: {}
  template:
    metadata:
      labels:
        app: golang-api
    spec:
      containers:
      - image: igoreulalio/repository-service:v3
        env: 
          - name: OTEL_COLLECTOR_ENDPOINT
            value: otel-collector-service
          - name: SERVICE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        envFrom:
          - secretRef:
              name: postgres-credentials
        name: repository-service
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "200m"
            memory: "300Mi"
status: {}