apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one
        resources:
          requests:
            cpu: "50m"
            memory: "1Gi"
          limits:
            cpu: "100m"
            memory: "1Gi"
        ports:
        - containerPort: 16686
        - containerPort: 14250
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
spec:
  selector:
    app: jaeger
  ports:
  - name: ui
    protocol: TCP
    port: 16686
    targetPort: 16686
  - name: collector
    protocol: TCP
    port: 14250
    targetPort: 14250
  type: ClusterIP
