apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9464"
        prometheus.io/path: "/metrics"
        prometheus.io/protocol: "http"
      labels:
        app: otel
    spec:
      containers:
        - name: collector
          image: otel/opentelemetry-collector-contrib:0.72.0
          resources:
            requests:
              cpu: "100m"
              memory: "350Mi"
            limits:
              cpu: "100m"
              memory: "350Mi"
          args: ["--config=/conf/collector-config.yaml"]
          ports:
            - containerPort: 9464
            - containerPort: 4317
            - containerPort: 4318
          volumeMounts:
            - name: otel-config
              mountPath: /conf
              readOnly: true
      volumes:
        - name: otel-config
          configMap:
            name: otel-config
            items:
              - key: collector-config.yaml
                path: collector-config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
data:
  collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
            cors:
              allowed_origins:
                - http://*
                - https://*
    exporters:
      prometheus:
        endpoint: "0.0.0.0:9464"
      jaeger:
        endpoint: "http://jaeger-service:14250"
        tls:
          insecure: true
    processors:
      batch:
    service:
      telemetry:
        logs:
          level: "debug"
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [jaeger]
          processors: [batch]
        metrics:
          receivers: [otlp]
          exporters: [prometheus]
          processors: [batch]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector-service
spec:
  selector:
    app: otel
  ports:
    - name: metrics
      protocol: TCP
      port: 9464
      targetPort: 9464
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: 4318
  type: ClusterIP

