apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: development
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'collector'
        static_configs:
          - targets: ['otel-collector-service:9464']
      - job_name: 'kubernetes-nodes-cadvisor'
        metrics_path: '/metrics/cadvisor'
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        tls_config:
          insecure_skip_verify: true
        scheme: https
        kubernetes_sd_configs:
          - role: node
            api_server: https://kubernetes.default.svc
            tls_config:
              insecure_skip_verify: true
            authorization:
              credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - source_labels: [__address__]
            regex: '([^:]+):.*'
            target_label: __address__
            replacement: '$1:10250'
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--log.level=debug"
        resources:
          requests:
            cpu: "100m"
            memory: "750Mi"
          limits:
            cpu: "100m"
            memory: "750Mi"
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yaml
        - name: token-volume
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config
      - name: token-volume
        projected:
          sources:
          - serviceAccountToken:
              path: token
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: development
spec:
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-clusterrole
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: development
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-clusterrole
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: development

