apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: repository-service
  name: repository-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repository-service
  strategy: {}
  template:
    metadata:
      labels:
        app: repository-service
    spec:
      containers:
      - image: igoreulalio/repository-service:v6-a
        env: 
          - name: OTEL_COLLECTOR_ENDPOINT
            value: otel-collector-service
          - name: SERVICE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: RABBITMQ_HOST
            value: rabbitmq-service
          - name: RABBITMQ_PORT
            value: "5672"
          - name: DB_HOST
            value: postgres-service
          - name: CONFIGURATION_SERVICE_URL
            value: http://configuration-service:8081
        envFrom:
          - secretRef:
              name: postgres-credentials
        name: repository-service
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "200m"
            memory: "300Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: repository-service
spec:
  selector:
    app: repository-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP